Src/Frontend/Frontend/Controllers/BookController.cs
using Frontend.Endpoints;
using Frontend.Models;
using HelloBook_Api._.Protos;
using Microsoft.AspNetCore.Mvc;
using Shared.Extensions;
using System.Diagnostics;

namespace Frontend.Controllers
{
    [Route("[controller]")]
    public class BookController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly Book_Endpoint _bookEndpoint;
        private readonly BookProto.BookProtoClient _bookClient;

        public BookController(ILogger<HomeController> logger
            , Book_Endpoint bookEndpoint
            , BookProto.BookProtoClient bookClient
            )
        {
            _logger = logger;
            _bookEndpoint = bookEndpoint;
            _bookClient = bookClient;
        }

        [HttpGet("get-books")]
        public async Task<IActionResult> GetBooks()
        {
            return View();
        }

        [HttpGet("get-books-api")]
        public async Task<IActionResult> GetBooksApi()
        {
            var data = await _bookEndpoint.Get_Books();
            return Ok(data);
        }

        [HttpPost("get-books-api")]
        public async Task<IActionResult> Add_Book([FromForm] string values)
        {
            var valuesObject = values.ToJsonObject<CobaPost>();
            var result = await _bookClient.Add_BookAsync(new Add_Book_Request
            {
                Author = valuesObject.Author,
                Title = valuesObject.Title,
                UnitPrice = valuesObject.UnitPrice
            });
            return Ok(result);
        }

        [HttpDelete("get-books-api")]
        public async Task<IActionResult> Remove_Book([FromForm] string key)
        {
            var result = await _bookClient.Remove_BookAsync(new Remove_Book_Request
            {
                Id = key
            });
            return Ok(result);
        }
    }

    public class CobaPost
    {
        public string Author { get; set; }
        public string Title { get; set; }
        public int UnitPrice { get; set; }
    }
}

Src/Frontend/Frontend/Controllers/CatalogController.cs
using Frontend.Endpoints;
using Frontend.Models;
using HelloBook_Api._.Protos;
using Microsoft.AspNetCore.Mvc;
using Shared.Extensions;
using System.Diagnostics;

namespace Frontend.Controllers
{
    [Route("[controller]")]
    public class CatalogController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly BookProto.BookProtoClient _bookClient;

        public CatalogController(ILogger<HomeController> logger
            , BookProto.BookProtoClient bookClient
            )
        {
            _logger = logger;
            _bookClient = bookClient;
        }

        [HttpGet()]
        public async Task<IActionResult> Get_CatalogBooks()
        {
            var result = await _bookClient.Get_CatalogBooksAsync(new Get_CatalogBooks_Request());
            ViewBag.CatalogBooks = result.Data.ToList();
            return View();
        }

        [HttpGet("get-catalogbooks-api")]
        public async Task<IActionResult> Get_CatalogBooksApi()
        {
            var result = await _bookClient.Get_CatalogBooksAsync(new Get_CatalogBooks_Request());
            return Ok(result);
        }
    }


}

Src/Frontend/Frontend/Views/Shared/_Layout.cshtml
@using Frontend._


@inject UserLogin _userLogin

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Frontend</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Frontend.styles.css" asp-append-version="true" />


    <!-- DevExtreme theme -->
    <link rel="stylesheet" href="https://cdn3.devexpress.com/jslib/22.1.3/css/dx.light.css">


</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Frontend</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Catalog" asp-action="Get_CatalogBooks">Catalog</a>
                        </li>


                        @if (_userLogin.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Basket" asp-action="Get_Baskets">Basket</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Identity" asp-action="Logout">Logout</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="GetBooks">Book (ADMIN)</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Identity" asp-action="Login">Login</a>
                            </li>

                             <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Identity" asp-action="Register">Register</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Frontend - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <!-- DevExtreme library -->
    <script type="text/javascript" src="https://cdn3.devexpress.com/jslib/22.1.3/js/dx.all.js"></script>
    <script src="https://unpkg.com/devextreme-aspnet-data/js/dx.aspnet.data.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>